apiVersion: apps/v1
kind: Deployment
metadata:
  name: converso-distancia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converso-distancia
  template:
    metadata:
      labels:
        app: converso-distancia
    spec:
      containers:
      - name: converso-distancia
        image: arauj0vini/converso-distancia:v1
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: converso-distancia
spec:
  selector:
    app: converso-distancia
  ports:
  - port: 80
    targetPort: 5000  
  type: NodePort